name: Something
on: {push: {branches: [trunk]}}
jobs:
  something_else:
    runs-on: macos-latest
    steps:
      - {name: Checkout, uses: actions/checkout@v4}
      - {name: won, run: "exec ./run"}
